### ISSUE TITLE
HACS installs to /config/netdaemon, not /config/netdaemon3 like the docs specify

### ISSUE THREAD

**Issue by Intecpsp** [ElVit/netdaemon-notify-on-update#1]
Title says it all. I was wondering why I hadn't been getting notifications from this automation and looked into my config folder to find a netdaemon folder along with the netdaemon3 folder I was expecting. After opening the netdaemon folder I found this automation sitting and waiting to be activated.

**Comment by ElVit** [comment]
Hi thanks for your feedback. 
Can you tell me where the docs specifies this? A link would be great. 
I followed the the instructions from [here](https://hacs.xyz/docs/categories/netdaemon_apps). I can not see an option there to define a path where the automation will be installed to.

**Comment by ElVit** [comment]
Oh think I see the problem. If you install the v3 addon the default path for the option "app_config_folder" is set to "/config/netdaemon3". You have to change this value to "/config/netdaemon". I think that's because the v3 addon is still in Beta phase. 
I will add this hint to my docs 😉

**Comment by Intecpsp** [comment]
Yeah, you found it. Instead of changing the config, wouldn't it be better to use the netdaemon3 folder? If other automations start using the new folder, but yours is using the old folder, we then have to pick which one(s) we want.

**Comment by ElVit** [comment]
Yes I agree, but unfortunatelly as far as I know it is not possible to change the installation path for netdaemon apps if installing them over hacs. If you know a way to change this behavior please tell me.

As I told before I think it is beacuse netdaemon v3 is still in beta. In my opinion a better approach would be to ask the netdaemon developers to change the default path of the addon.
