### ISSUE TITLE
In Docker Container, "Get Supervisor Token failed" ERR 3 times every minute

### ISSUE THREAD

**Issue by tonysurma** [ElVit/netdaemon-notify-on-update#2]
I don't think there is a config option to not check for supervisor version when you are running in something like docker.

That is why I am seeing this in my logs roughly every minute:

```
[20:00:48 ERR] NotifyOnUpdate.NotifyOnUpdateApp: Get Supervisor Token failed
[20:00:48 ERR] NotifyOnUpdate.NotifyOnUpdateApp: Get Supervisor Token failed
[20:00:48 ERR] NotifyOnUpdate.NotifyOnUpdateApp: Get Supervisor Token failed
```

Any option to stop that check via config maybe?

Thanks

**Comment by ElVit** [comment]
Hi @tonysurma,
thanks for using my NetDeamon app 😃
Yes an option for the supervisor addon updates makes sense, didn't thought about that.
I will implement it as soon as possible.

**Comment by ElVit** [comment]
So I added an option where you can choose for which update types you want to get notifications.
Just remove the `Supervisor` type from the list and the errors should disappear.

Can you please verify if its working for you?

**Comment by tonysurma** [comment]
I am going to restart and verify I have latest a few more times but currently I still get that error with what I think is the update.  Will report back

**Comment by tonysurma** [comment]
I will test other combinations but it appears so far that I need to remove all but the HACS option when running in a docker container to remove that issue.

**Comment by tonysurma** [comment]
Verified by testing and looking at the code.  This is now okay, just need to remember/note to remove everything but HACS for docker.

You can close this issue.  I will separately investigate if there is a way to find the version status of a docker instance.

Thanks!

**Comment by tonysurma** [comment]
Turns out this integration if you choose website as the source, will do exactly that.  https://www.home-assistant.io/integrations/version/

**Comment by ElVit** [comment]
Thanks for testing @tonysurma. 
Yes I think for your setup only the HACS updates will work. Unfortunately I have no docker setup here to implement it for this use case. 
But I am working on a new feature for this app. This will check the update entities instead of using the REST API. And hopefully it will also work better for docker users. 
The code is already available on the dev branch. You are welcome to test it 😃.
