### ISSUE TITLE
Documentation needs to be updated with new install method

### ISSUE THREAD

**Issue by Intecpsp** [ElVit/netdaemon-notify-on-update#4]
With HACS [deprecating NetDaemon](https://github.com/hacs/integration/pull/3066), the documentation for installing this automation needs to be updated. 

https://hacs.xyz/docs/categories/netdaemon_apps/

https://netdaemon.xyz/docs/v3/started/hacs/

**Comment by ElVit** [comment]
Removed this repo from HACS.
